name: Publish to MSStore
runs-on: windows-latest
steps:
      # <previous steps to prepare workspace>
    name: Setup MSbuild
    uses: microsoft/setup-msbuild@v1.3.1
    name: Configure the Microsoft Store CLI
    run: |
      Install-Module -Name StoreBroker -Force
    name: Upload to MSStore
    env:
      CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
    run: |
      # Login
      $user = $Env:CLIENT_ID
      $password = ConvertTo-SecureString $Env:CLIENT_SECRET -AsPlainText -Force
      $Cred = New-Object System.Management.Automation.PSCredential($user, $password)
      Set-StoreBrokerAuthentication -TenantId ${{ secrets.MS_TENANT_ID }} -Credential $Cred
      $appId = "9PNR1H0WT6RW"
      # Create submission package
      New-StoreBrokerConfigFile -Path submission.json -AppId 9PNR1H0WT6RW
      New-SubmissionPackage -ConfigPath .\submission.json -AppxPath .\Tonbrett.msix -OutPath out -OutName package
      # Create new submission
      $sub = New-ApplicationSubmission -AppId $appId -Force
      # Parse submission meta
      $json = (Get-Content out\package.json -Encoding UTF8) | ConvertFrom-Json
      # Delete old packages
      foreach ($package in $sub.applicationPackages) {
        $package.fileStatus = "PendingDelete"
      }
      # add new packages
      $sub.applicationPackages += $json.applicationPackages
      # Upload submission meta
      Set-ApplicationSubmission -AppId $appId -UpdatedSubmission $sub
      # Upload submission package
      Set-SubmissionPackage -PackagePath out\package.zip -UploadUrl ($sub.fileUploadUrl)
      # Commit changes
      Complete-ApplicationSubmission -AppId $appId -SubmissionId ($sub.id)
